Bingocell.create(bingocell: "Someone falls asleep")
Bingocell.create(bingocell: "Walt reiterates what someone says.")
Bingocell.create(bingocell: "Sherif is brutally honest")
Bingocell.create(bingocell: "Dan volunteers to organize something")
Bingocell.create(bingocell: "Lecture runs over 30 minutes late.")
Bingocell.create(bingocell: "Someone has no idea where their accountability buddy is")
Bingocell.create(bingocell: "No one knows what Peter is talking about.")
Bingocell.create(bingocell: "Richard tells a crazy story.")
Bingocell.create(bingocell: "Someone is on Facebook or Reddit.")
Bingocell.create(bingocell: "Jessie R. corectly answers two questions in a row.")
Bingocell.create(bingocell: "Someones phone goes off.")
Bingocell.create(bingocell: "Stu runs or skips.")
Bingocell.create(bingocell: "Amadou says 'awesome'.")
Bingocell.create(bingocell: "Someone posts resource to G+ mid-lecture")
Bingocell.create(bingocell: "Adell is annoyed were not on schedule.")
Bingocell.create(bingocell: "Someone asks if teacher can post the lecture on GitHub.")
Bingocell.create(bingocell: "Someone is eating.")
Bingocell.create(bingocell: "Lucas asks a super advanced question.")
Bingocell.create(bingocell: "Randy codes through the entire lecture.")
Bingocell.create(bingocell: "Ram asks for clarification.")
Bingocell.create(bingocell: "How would you test this?")
Bingocell.create(bingocell: "Sherif asks Stu for confirmation. Stu wasn't paying attention.")
Bingocell.create(bingocell: "A random person ducks under projecter while passing by.")
Bingocell.create(bingocell: "Lecture goes 10 minutes over anticipated end time.")
Bingocell.create(bingocell: "Projector screen randomly turns off.")
Bingocell.create(bingocell: "Someone leaves to code less than 30 minutes into a lecture")
Bingocell.create(bingocell: "Maurits makes up an English word.")

